### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by BolivarTech** [sony/easyhttpcpp#8]
Hello,

Really this is not an issue, I'm trying to connect to an apache server with a self-signed certificate and I can't find a way to ignore this error.

Error occurred: EASYHTTPCPP-ERR-100704: SSL error occurred in sendRequest. [scheme=https, host=https://*********.com] message=[error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed]

Any suggestions on how to solve this?

Regards and thanks,

Julian Bolivar

**Comment by shekharhimanshu** [comment]
Hi Julian Bolivar,

Thank you for your interest in EasyHttp.
We use self-signed certificates for our unit testing, so specification wise you should be able to connect to servers with self-signed certificates as well. For example, https://self-signed.badssl.com/
EasyHttp does not explicitly check for self-signed certificates.

Could you please share the following info?

- Poco version
- OpenSSL version

>error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

After looking up this error online, I would suggest checking the following points:

- Check if your device's time is correct
- Check if your device's cacert is correct. (you can download from here as well, https://curl.haxx.se/ca/cacert.pem)

**Comment by BolivarTech** [comment]
Fixed the issue,

Thanks and appreciated for your help

Julian Bolivar

**Comment by shekharhimanshu** [comment]
Hi @BolivarTech 

Happy to know you were able to fix the issue. 👍 
Could you share with us what the issue was and how you fixed it?

Thanks!

**Comment by shekharhimanshu** [comment]
Closing the issue because of inactivity.
